#!/usr/bin/env node

/**
 * Hook to load .env variables into www/js/env.js before cordova prepare/build
 */

const fs = require('fs');
const path = require('path');

module.exports = function (context) {
    const projectRoot = context.opts.projectRoot || path.resolve(__dirname, '..');
    const envFile = path.join(projectRoot, '.env');
    const envExampleFile = path.join(projectRoot, '.env.example');
    const outputJs = path.join(projectRoot, 'www/js/env.js');

    let siteId = process.env.SHIELD_SITE_ID || '';
    let secretKey = process.env.SHIELD_SECRET_KEY || '';

    function parseEnv(filePath) {
        const env = {};
        if (!fs.existsSync(filePath)) return env;
        const content = fs.readFileSync(filePath, 'utf8');
        const lines = content.split('\n');
        for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith('#')) continue;
            const eqIdx = trimmed.indexOf('=');
            if (eqIdx !== -1) {
                const key = trimmed.substring(0, eqIdx).trim();
                let val = trimmed.substring(eqIdx + 1).trim();
                if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
                    val = val.substring(1, val.length - 1);
                }
                env[key] = val;
            }
        }
        return env;
    }

    const fileEnv = parseEnv(fs.existsSync(envFile) ? envFile : envExampleFile);

    if (!siteId && fileEnv.SHIELD_SITE_ID) {
        siteId = fileEnv.SHIELD_SITE_ID;
    }
    if (!secretKey && fileEnv.SHIELD_SECRET_KEY) {
        secretKey = fileEnv.SHIELD_SECRET_KEY;
    }

    siteId = siteId || 'SITE_ID';
    secretKey = secretKey || 'SECRET_KEY';

    const content = `/* Auto-generated by hooks/load-env.js */
window.SHIELD_ENV = {
    SHIELD_SITE_ID: ${JSON.stringify(siteId)},
    SHIELD_SECRET_KEY: ${JSON.stringify(secretKey)}
};
`;

    fs.mkdirSync(path.dirname(outputJs), { recursive: true });
    fs.writeFileSync(outputJs, content, 'utf8');
    console.log(`[Env Hook] Generated www/js/env.js (Site ID: ${siteId === 'SITE_ID' || siteId === 'your_shield_site_id_here' ? '[Default/Placeholder]' : '[Configured]'})`);
};
